//Création des User
POST http://localhost:8080/user
Content-Type: application/json

{"id":5, "name":"toto", "surname":"bobby"}

###

POST http://localhost:8080/user
Content-Type: application/json

{"id":6, "name":"Charles", "surname":"Charly"}

###
//Liste des user
GET http://localhost:8080/user
Accept: application/json

###

//1 user
GET http://localhost:8080/user/5
Accept: application/json

###

//1 user qui n'hesite pas
GET http://localhost:8080/user/7
Accept: application/json

###

//On supprime
DELETE http://localhost:8080/user/5
Accept: application/json

###
//Liste des users un de moins normalement
GET http://localhost:8080/user
Accept: application/json

###